project_name: go-project

release:
  draft: true
  name_template: '{{.ProjectName}} {{ trimprefix .Tag "cli-" }}'

before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./main.go
    binary: hello-world
archives:
  # default format for Mac (darwin) and Linux
  - format: tar.gz
    # if the OS is windows, we override and put everything in a .zip instead.
    format_overrides:
        - goos: windows
          format: zip
    name_template: '{{.ProjectName}}_{{ trimprefix .Version "cli-" }}_{{.Os}}-{{.Arch}}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
